version: "3.1"

services:
 db:
    image: mariadb
    command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON
    environment:
      MYSQL_ROOT_PASSWORD: 34n3aWkERifEo8
    volumes: 
      - ${DB_PATH_HOST}:${DB_PATH_IN_CONTAINER} 
      - ./mysql/conf:/etc/mysql/conf.d

 nginx: 
    image: nginx
    links:
      - php-fpm
      - db
    volumes: 
      - ${APP_PATH_HOST}:${APP_PATH_IN_CONTAINER} 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 80:80

 php-fpm:
    build: ./php-fpm
    volumes: 
      - ${APP_PATH_HOST}:${APP_PATH_IN_CONTAINER}
